CREATE TABLE IF NOT EXISTS donors_v2 (
    id                          SERIAL PRIMARY KEY,
    user_id                     TEXT,
    bridge_id                   TEXT,
    role                        TEXT,
    role_status                 BOOLEAN,
    bridge_status               BOOLEAN,
    blood_group                 TEXT,
    gender                      TEXT,
    latitude                    DOUBLE PRECISION,
    longitude                   DOUBLE PRECISION,
    bridge_gender               TEXT,
    bridge_blood_group          TEXT,
    quantity_required           INTEGER,
    last_transfusion_date       TEXT,
    expected_next_transfusion_date TEXT,
    registration_date           TEXT,
    donor_type                  TEXT,
    last_contacted_date         TEXT,
    last_donation_date          TEXT,
    next_eligible_date          TEXT,
    donations_till_date         INTEGER,
    eligibility_status          TEXT,
    cycle_of_donations          INTEGER,
    total_calls                 INTEGER,
    frequency_in_days           INTEGER,
    status_of_bridge            BOOLEAN,
    status                      TEXT,
    donated_earlier             BOOLEAN,
    last_bridge_donation_date   TEXT,
    calls_to_donations_ratio    DOUBLE PRECISION,
    user_donation_active_status TEXT,
    inactive_trigger_comment    TEXT,
    response_rate               DOUBLE PRECISION,
    active_score                DOUBLE PRECISION,
    days_since_last_donation    INTEGER,
    donor_availability_score    DOUBLE PRECISION,
    donor_rank                  INTEGER,
    total_score                 DOUBLE PRECISION,
    contact_number              TEXT
);
